apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-k8s-app
  template:
    metadata:
      labels:
        app: simple-k8s-app
    spec:
      containers:
        - name: simple-k8s-app
          image: simple-k8s-app:20240327212332
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
