apiVersion: v1
kind: Service
metadata:
  name: cyber-mavericks
spec:
  type: NodePort
  selector:
    app: cyber-mavericks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
