apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-app
spec:
  type: NodePort
  selector:
    app: simple-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
